knp_snappy:
    pdf:
    
        enabled: true
        binary: '"C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe"'
        options:
            enable-local-file-access: true
            encoding: 'UTF-8'
            margin-top: 0
            margin-bottom: 0
            margin-left: 0
            margin-right: 0
            
