payum:
    storages:
        App\Entity\Payment:
            doctrine: orm

    security:
        token_storage:
            Payum\Core\Model\Token:
                filesystem:
                    storage_dir: '%kernel.project_dir%/var/payum/gateways'
                    id_property: hash

    gateways:
        stripe_checkout:
            factory: stripe_checkout
            publishable_key: '%env(STRIPE_PUBLIC_KEY)%'
            secret_key: '%env(STRIPE_SECRET_KEY)%'

