symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600                  # Token lifetime in seconds (1 hour)
    throttle_limit: 60              # Reduced throttle time to 1 minute for easier testing
    enable_garbage_collection: true # Automatically remove expired tokens
